name: arm-ams-short-course-2024-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - xarray
  - dask
  - arm_pyart
  - act-atmos
  - matplotlib
  - jupyter_server
  - pip
  - pip:
      - sphinx-pythia-theme
